### ISSUE TITLE
What is classpath

### ISSUE THREAD

**Issue by VenoPhage** [TheDialgaTeam-Project-Zomboid-Mods/PZ-Discord-Patch#1]
I know nothing about java, what is the "classpath" mentioned in installation?

**Comment by jianmingyong** [comment]
> I know nothing about java, what is the "classpath" mentioned in installation?

Inside the bat/sh file (which you use to launch the server), there is a line called classpath that includes a list of java files to load in the order it was specified.

You need to manually add the location where you have placed the new java file to load this mod. It must be placed first followed by the original list of java files that it comes with.

If you use the executable rather than bat/sh file, you should edit the corresponding json file instead.

**Comment by VenoPhage** [comment]
So incase of a server host that doesnt give access to this (which is common with dedicated) is this just not a usable patch?

**Comment by jianmingyong** [comment]
> So incase of a server host that doesnt give access to this (which is common with dedicated) is this just not a usable patch?

Yea. I am sorry but that is indeed the case. If you have no access to the base file, you are unable to do anything about it.
